# Generated by Django 5.1.4 on 2025-01-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyBudgetLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cate", models.CharField(default="General", max_length=100)),
                ("budget_limit", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ExpensesTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("transportation", "Transportation"),
                            ("utilities", "Utilities"),
                            ("entertainment", "Entertainment"),
                            ("alcohol", "Alcohol"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "bill_image",
                    models.ImageField(blank=True, null=True, upload_to="bill_images/"),
                ),
            ],
        ),
    ]
